//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThamQuanTDMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int AD_Id { get; set; }
        public string AD_Name { get; set; }
        public Nullable<System.DateTime> AD_Birth { get; set; }
        public string AD_Username { get; set; }
        public string AD_Password { get; set; }
    }
}
