//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThamQuanTDMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOTER_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOTER_TYPE()
        {
            this.FOOTERs = new HashSet<FOOTER>();
        }
    
        public int FooterType_ID { get; set; }
        public string Footer_Type1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOOTER> FOOTERs { get; set; }
    }
}
