//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThamQuanTDMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOTER
    {
        public int Footer_Id { get; set; }
        public string Footer_Name { get; set; }
        public string Footer_Link { get; set; }
        public string Footer_Images { get; set; }
        public string Footer_Content { get; set; }
        public Nullable<int> FooterType_ID { get; set; }
    
        public virtual FOOTER_TYPE FOOTER_TYPE { get; set; }
    }
}
