//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThamQuanTDMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_CONTENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU_CONTENT()
        {
            this.SUB_MENU_CONTENT = new HashSet<SUB_MENU_CONTENT>();
        }
    
        public int MC_Id { get; set; }
        public string MC_Title { get; set; }
        public string MC_Images { get; set; }
        public string MC_Position { get; set; }
        public string MC_Description { get; set; }
        public string MC_Sources { get; set; }
        public string MC_Content { get; set; }
        public string MC_Note { get; set; }
        public string MC_Paths { get; set; }
        public int Menu_Id { get; set; }
        public int Department_Id { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual MENU MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUB_MENU_CONTENT> SUB_MENU_CONTENT { get; set; }
    }
}
