//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThamQuanTDMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.MENU_CONTENT = new HashSet<MENU_CONTENT>();
            this.STUDY_ACTIVITY = new HashSet<STUDY_ACTIVITY>();
            this.STUDY_ENVIRONMENT = new HashSet<STUDY_ENVIRONMENT>();
        }
    
        public int Menu_Id { get; set; }
        public string Menu_Name { get; set; }
        public string Menu_color { get; set; }
        public string Menu_Link { get; set; }
        public Nullable<int> Menu_Active { get; set; }
        public string Menu_Note { get; set; }
        public string Menu_Paths { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_CONTENT> MENU_CONTENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDY_ACTIVITY> STUDY_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDY_ENVIRONMENT> STUDY_ENVIRONMENT { get; set; }
    }
}
