//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThamQuanTDMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDY_ENVIRONMENT
    {
        public int SE_Id { get; set; }
        public string SE_Title { get; set; }
        public string SE_Content { get; set; }
        public string SE_Image { get; set; }
        public string SE_Note { get; set; }
        public Nullable<int> Menu_Id { get; set; }
        public int SE_Type { get; set; }
    
        public virtual MENU MENU { get; set; }
    }
}
