//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThamQuanTDMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_MENU_CONTENT
    {
        public int SMC_Id { get; set; }
        public string SMC_Images { get; set; }
        public string SMC_Position { get; set; }
        public string SMC_Description { get; set; }
        public string SMC_Note { get; set; }
        public int MC_Id { get; set; }
    
        public virtual MENU_CONTENT MENU_CONTENT { get; set; }
    }
}
