//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThamQuanTDMU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDMU_INTRODUCTIONEntities : DbContext
    {
        public TDMU_INTRODUCTIONEntities()
            : base("name=TDMU_INTRODUCTIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<FOOTER> FOOTERs { get; set; }
        public virtual DbSet<FOOTER_TYPE> FOOTER_TYPE { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<MENU_CONTENT> MENU_CONTENT { get; set; }
        public virtual DbSet<STUDY_ACTIVITY> STUDY_ACTIVITY { get; set; }
        public virtual DbSet<STUDY_ENVIRONMENT> STUDY_ENVIRONMENT { get; set; }
        public virtual DbSet<SUB_MENU_CONTENT> SUB_MENU_CONTENT { get; set; }
        public virtual DbSet<VISIT_IMAGE> VISIT_IMAGE { get; set; }
    }
}
