//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThamQuanTDMU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISIT_IMAGE
    {
        public int Img_Id { get; set; }
        public string Img_Src { get; set; }
        public string Img_Title { get; set; }
        public string Img_Link { get; set; }
        public string area { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lng { get; set; }
    }
}
